apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  project: default
  source:
    repoURL: http://gitlab-service.gitlab.svc.cluster.local/root/yismaili.git/
    path: dev
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true