apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: gitlab
spec:
  selector:
    app: gitlab-ce
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

