apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  type: NodePort 
  ports:
  - name: 8888-8888
    nodePort: 3000
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: app