# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  # Set up the Server
  config.vm.box = "debian/buster64" 
  config.vm.box_url = "https://app.vagrantup.com/debian/boxes/buster64"
  
  config.vm.define 'yismailiS' do |server|
    server.vm.hostname = 'yismailiS'
    server.vm.network 'private_network', ip: '192.168.56.110'
    # VirtualBox provider settings
    server.vm.provider 'virtualbox' do |vb|
      # vb.name = "yismailiS"
      vb.cpus = 1
      vb.memory = 1024
    end

    server.vm.provision "shell", path: "scripts/setup-env.sh", privileged: false if Vagrant::Util::Platform.linux?
    server.vm.provision "shell", path: "scripts/deploy-app.sh", privileged: false if Vagrant::Util::Platform.linux?
    
    # Synced folder
    server.vm.synced_folder "confs/", "/vagrant", owner: "root", group: "root"
  end
end
