# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  # Set up the Server
  config.vm.define 'yismaili' do |server|
    server.vm.box = 'debian/buster64'
    server.vm.hostname = 'ServerS'
    
    # Configure eth1 with a dedicated IP
    server.vm.network 'private_network', type: 'static', ip: '192.168.56.110', virtualbox__intnet: 'eth1'
    
    # VirtualBox provider settings
    server.vm.provider 'virtualbox' do |vb|
      vb.name = 'Server_nginx'
      vb.cpus = 2
      vb.memory = 10240  # 10 GB 
    end
    
    # Enable passwordless SSH
    server.vm.provision "shell", path: "scripts/provision.sh", privileged: false if Vagrant::Util::Platform.linux?
    
    # Synced folder
    server.vm.synced_folder "confs/", "/vagrant", owner: "root", group: "root"
  end
end


