# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  # Set up the Server
  config.vm.define 'yismaili' do |server|
    server.vm.box = 'debian/buster64'
    server.vm.hostname = 'ServerS'
    
    /r.vm.provider 'virtualbox' do |vb|
      vb.name = 'Server_nginx'
      vb.cpus = 1
      vb.memory = 1024
    end

    # Enable passwordless SSH
    server.vm.provision "shell", path: "scripts/provision.sh", privileged: false if Vagrant::Util::Platform.linux?

    # Synced folder configuration
    server.vm.synced_folder "./confs", "/vagrant", disabled: true
  end
end


