# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# Vagrant.configure('2') do |config|
#   # set up  the Server
#   config.vm.define 'yismaili' do |server|
#     server.vm.box = 'debian/buster64'
#     server.vm.hostname = 'ServerS'
#     server.vm.provider 'virtualbox' do |vb|
#       vb.name = 'Server_nginx'
#       vb.cpus = 1
#       vb.memory = 512
#     end

#    end

#   # set up the ServerWorker
#   config.vm.define 'yismaili_1' do |server_worker|
#     server_worker.vm.box = 'debian/buster64'
#     server_worker.vm.hostname = 'ServerWorkerSW'
#     server_worker.vm.provider 'virtualbox' do |vb|
#       vb.name = 'ServerWorker_nginx'
#       vb.cpus = 1
#       vb.memory = 512
#     end

#   end

# end


Vagrant.configure('2') do |config|
  # Set up the Server
  config.vm.define 'yismaili' do |server|
    server.vm.box = 'debian/buster64'
    server.vm.hostname = 'ServerS'
    
    # Configure eth1 with a dedicated IP
    server.vm.network 'private_network', type: 'dhcp', virtualbox__intnet: 'eth1'
    
    # VirtualBox provider settings
    server.vm.provider 'virtualbox' do |vb|
      vb.name = 'Server_nginx'
      vb.cpus = 1
      vb.memory = 512
    end

    # Enable passwordless SSH
    server.vm.provision 'shell', inline: <<-SHELL
      mkdir -p ~/.ssh
      chmod 700 ~/.ssh
      ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -N ""
      cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
      chmod 600 ~/.ssh/authorized_keys
    SHELL
  end

  # Set up the ServerWorker
  config.vm.define 'yismaili_1' do |server_worker|
    server_worker.vm.box = 'debian/buster64'
    server_worker.vm.hostname = 'ServerWorkerSW'
    
    # Configure eth1 with a dedicated IP
    server_worker.vm.network 'private_network', type: 'dhcp', virtualbox__intnet: 'eth1'
    
    # VirtualBox provider settings
    server_worker.vm.provider 'virtualbox' do |vb|
      vb.name = 'ServerWorker_nginx'
      vb.cpus = 1
      vb.memory = 512
    end

    # Enable passwordless SSH
    server_worker.vm.provision 'shell', inline: <<-SHELL
      mkdir -p ~/.ssh
      chmod 700 ~/.ssh
      ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -N ""
      cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
      chmod 600 ~/.ssh/authorized_keys
    SHELL
  end
end

