# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  # Set up the Server
  config.vm.box = "debian/buster64" 
  config.vm.box_url = "https://app.vagrantup.com/debian/boxes/buster64"

  config.vm.define 'yismailiS' do |server|
    server.vm.hostname = 'yismailiS'
    server.vm.network 'private_network', ip: '192.168.56.110'
    # VirtualBox provider settings
    server.vm.provider 'virtualbox' do |vb|
      # vb.name = "yismailiS"
      vb.cpus = 1
      vb.memory = 1024
    end
    server.vm.provision "shell", path: "scripts/server.sh", privileged: false if Vagrant::Util::Platform.linux?
  end

  config.vm.define 'yismailiSW' do |serverWorker|

    serverWorker.vm.hostname = 'yismailiSW'
    serverWorker.vm.network 'private_network', ip: '192.168.56.111'
    serverWorker.vm.provider 'virtualbox' do |vb|
      # vb.name = "yismailiSW"
      vb.cpus = 1
      vb.memory = 1024
    end

    serverWorker.vm.provision "shell", path: "scripts/serverWorker.sh", privileged: false if Vagrant::Util::Platform.linux?
  end
end

