# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure('2') do |config|

  config.vm.boot_timeout = 300 # Increase to 10 minutes (adjust as needed)
  # set up the first machine (Server)
  config.vm.define 'yismaili' do |server|
    server.vm.box = 'debian/buster64'
    server.vm.hostname = 'ServerS'
    # server.vm.network 'private_network', type: 'dhcp', adapter: 1
    # server.vm.network 'private_network', type: 'static', ip: '192.168.56.110', adapter: 2
    server.vm.provider 'virtualbox' do |vb|
      vb.name = 'Server_nginx'
      vb.cpus = 1
      vb.memory = 512
    end

    # SSH Configuration for Server
    # config.ssh.insert_key = true
    # config.ssh.private_key_path = "/home/dexters/.ssh/id_rsa" # path of private key
    # config.ssh.forward_agent = true
    # server.ssh.username = 'vagrant'
   end

  # set up the second machine (ServerWorker)
  config.vm.define 'yismaili_1' do |server_worker|
    server_worker.vm.box = 'debian/buster64'
    server_worker.vm.hostname = 'ServerWorkerSW'
    # server_worker.vm.network 'private_network', type: 'dhcp', adapter: 1
    # server_worker.vm.network 'private_network', type: 'static', ip: '192.168.56.111', adapter: 2
    server_worker.vm.provider 'virtualbox' do |vb|
      vb.name = 'ServerWorker_nginx'
      vb.cpus = 1
      vb.memory = 512
    end

  #   # SSH Configuration for ServerWorker
  #   config.ssh.insert_key = true
  #   config.ssh.private_key_path = "~/.ssh/id_rsa" # path of private key
  #   server_worker.ssh.username = 'vagrant'
  end

end

