apiVersion: v1
kind: Service
metadata:
  name: wil42-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: wil42
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
